server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
